version: "3.8"

x-common-env: &common_env
  SESSION: "default"
  REDIS_SERVER: "redis:6379"

services:
  # base:
  #   image: pythoncv
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile-base
  # objectdetector:
  #   image: objectdetector:latest
  #   container_name: objectdetector
  #   build:
  #     context: ../src
  #     dockerfile: ./objectdetector/Dockerfile
  #   depends_on:
  #     # - base
  #     - redis
  #   volumes:
  #     - ./networks:/networks
  #     - ./networks/ssd_mobilenet_v2_coco_2018_03_29/saved_model:/data/saved_model
  #     - ./video.mp4:/video.mp4
  #   environment:
  #     <<: *common_env
  #     # SOURCE: "rtsp://admin:admin@192.168.1.168:80"
  #     SOURCE: "/video.mp4"
  #     #SOURCE: 0
  #     FROZEN_MODEL: "/data/saved_model"
  #     THREASHOLD: 0.4
  #     DELAY: 1.0
  #   restart: always
  redis:
    image: redis:6.0.9-alpine
    container_name: redis
    ports:
      - 6379:6379
