version: "3.8"

x-common-env: &common_env
  SESSION: "default"
  REDIS_SERVER: "redis:6379"
  ZMQ: "zmq:3000"

services:
  base:
    image: pythoncv
    build:
      context: .
      dockerfile: ./Dockerfile-base
  camerasource:
    image: camerasource:latest
    container_name: camerasource
    build:
      context: ../src
      dockerfile: ./camerasource/Dockerfile
    depends_on:
      - base
      - redis
    environment:
      <<: *common_env
      SOURCE: "rtsp://admin:admin@192.168.1.168:80"
    restart: always
  objectdetector:
    image: objectdetector:latest
    container_name: objectdetector
    build:
      context: ../src
      dockerfile: ./objectdetector/Dockerfile
    depends_on:
      - base
      - redis
      - zmq
    volumes:
      - ./networks:/networks
    environment:
      <<: *common_env
      NETWORK: "ssd-mobilenet-v2"
      OVERLAY: "box,labels,conf"
      THREASHOLD: 0.5
  redis:
    image: redis:6.0.9-alpine
    container_name: redis
    ports:
      - 6379:6379
  zmq:
    image: zeromq/zeromq:v3.2.5
    container_name: zmq
    ports: 
      - 3000:3000
