FROM debian:stable-slim

RUN pip install --upgrade pip

RUN mkdir /projects
WORKDIR /projects
RUN git clone https://github.com/tensorflow/models.git

WORKDIR /projects/models/research
RUN protoc object_detection/protos/*.proto --python_out=.
RUN cp object_detection/packages/tf2/setup.py .
RUN python -m pip install .


ENTRYPOINT /bin/sh
